version: '3'
services:
  service-discovery:
    image: mohammedusama/service-discovery:v1
    ports:
      - 8761:8761
    networks:
      - my-network

  api-gateway:
    image: mohammedusama/api-gateway:v1
    ports:
      - 8081:8081  # Assuming your user-service listens on port 
    #environment:
     # - eureka.instance.hostname=localhost
     # - eureka.instance.hostname=service-discovery
     # - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka

    networks:
      - my-network

  service-1:
    image: mohammedusama/service-1:v1
    ports:
      - 8082:8082
  #  environment:
  #    - eureka.instance.hostname=localhost
      #- eureka.instance.hostname=service-1
 #     - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka
    networks:
      - my-network

  service-2:
    image: mohammedusama/service-2:v1
    ports:
      - 8083:8083
    #environment:
     # - eureka.instance.hostname=service-2
      #- eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka
    networks:
      - my-network


networks:
  my-network: